### PR TITLE
Change Cirrus status link

### PR DESCRIPTION
**Pull request by amontoison**
close #15

### CODE REVIEW

**Comment by dpo** [comment]
Why is this closing #15?

**Comment by amontoison** [comment]
Because you already phased out julia 0.7 with a previous pull request and I added Windows in .travis.yml with this pull request.

**Comment by dpo** [comment]
Ah thank you ;-) Great to see that Travis/Windows is working now!!!

**Comment by amontoison** [comment]
With Yggdrasil / PROPACK_jll, we have much less problem!
The appveyor.yml is a bit old too. I will update it too :)

**Comment by dpo** [comment]
Much better! Thank you!

**Pull request merged**
